import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const SRC = new URL('../tokens/tokens.json', import.meta.url);
const OUT = new URL('../src/styles/tokens.css', import.meta.url);

const tree = JSON.parse(readFileSync(SRC, 'utf8'));

function flatten(node, path = [], out = []) {
  if (node && typeof node === 'object' && '$value' in node) {
    out.push({ path, value: node.$value });
  } else {
    for (const [key, child] of Object.entries(node)) flatten(child, [...path, key], out);
  }
  return out;
}

const raw = flatten(tree.raw);
const semantic = flatten(tree.semantic);
const known = new Set([...raw, ...semantic].map((t) => t.path.join('.')));
const varName = (path) => `--${path.join('-')}`;

function toCss(value) {
  const ref = /^\{(.+)\}$/.exec(value);
  if (!ref) return value;
  if (!known.has(ref[1])) throw new Error(`Unknown token reference: ${value}`);
  return `var(--${ref[1].replace(/\./g, '-')})`;
}

const lines = (tokens) => tokens.map((t) => `  ${varName(t.path)}: ${toCss(t.value)};`).join('\n');

const css = `/* Generated by scripts/build-tokens.mjs from tokens/tokens.json. Do not edit. */
:root {
  /* Raw tier */
${lines(raw)}

  /* Semantic tier: the only tier components may consume */
${lines(semantic)}
}
`;

mkdirSync(dirname(OUT.pathname), { recursive: true });
writeFileSync(OUT, css);
console.log(`tokens.css: ${raw.length} raw, ${semantic.length} semantic`);
